export enum AnalyticsAction {
  CUSTOMIZE = "customize",
  DEDICATE = "dedicate",
  DOWNLOAD = "download",
  CTA_WA_MODAL = "cta_whatsapp_modal",
  CTA_WA_POST_DOWNLOAD = "cta_whatsapp_post_download",
  CTA_WA_GALLERY = "cta_whatsapp_gallery",
  SHARE_CONFIRM_OPEN = "share_confirm_open",
  SHARE_CONFIRM_EXECUTED = "share_confirm_executed",
  GALLERY_CTA_CLICKED = "gallery_cta_clicked",
  GALLERY_VIEW = "gallery_view",
  GALLERY_OPENED = "gallery_opened",
  GALLERY_EMPTY_VIEW = "gallery_empty_view",
  GALLERY_SESSION_CLICK = "gallery_session_click",
  GALLERY_GRID_OPENED = "gallery_grid_opened",
  EVENT_EXPIRED_VIEW = "event_expired_view",
  IMAGINA_CTA_CLICKED = "imagina_cta_clicked",
  RECOVER_PHOTOS_CTA_CLICKED = "recover_photos_cta_clicked",
  SESSION_VIEW = "session_view",
  SESSION_OPENED = "session_opened",
  PHOTO_VIEW = "photo_view",
}
