export type MediaManifest = {
  sections: Array<{
    key: string;
    label: string;
    photos: Array<{
      src: string;
      fallbackSrc?: string;
      webp?: string;
      jpg?: string;
    }>;
    videos: Array<{
      src: string;
    }>;
  }>;
};

// Generated by your script (copied from /Users/robertotorres/Downloads/media.json).
// Source of truth for Fotos tabs + items (no Storage "list" calls needed).
export const MEDIA_MANIFEST: MediaManifest = {
  sections: [
    {
      key: "glitter bar",
      label: "Glitter Bar",
      photos: [
        {
          src: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/glitter%20bar/photo_265.webp",
          fallbackSrc:
            "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/glitter%20bar/photo_265.jpg",
          webp: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/glitter%20bar/photo_265.webp",
          jpg: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/glitter%20bar/photo_265.jpg",
        },
        {
          src: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/glitter%20bar/photo_274.webp",
          fallbackSrc:
            "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/glitter%20bar/photo_274.jpg",
          webp: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/glitter%20bar/photo_274.webp",
          jpg: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/glitter%20bar/photo_274.jpg",
        },
        {
          src: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/glitter%20bar/photo_293.webp",
          fallbackSrc:
            "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/glitter%20bar/photo_293.jpg",
          webp: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/glitter%20bar/photo_293.webp",
          jpg: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/glitter%20bar/photo_293.jpg",
        },
      ],
      videos: [],
    },
    {
      key: "make up",
      label: "Make Up",
      photos: [
        {
          src: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/make%20up/IMG_20231114_140229_318.webp",
          fallbackSrc:
            "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/make%20up/IMG_20231114_140229_318.jpg",
          webp: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/make%20up/IMG_20231114_140229_318.webp",
          jpg: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/make%20up/IMG_20231114_140229_318.jpg",
        },
        {
          src: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/make%20up/IMG_20250926_1440222.webp",
          fallbackSrc:
            "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/make%20up/IMG_20250926_1440222.jpg",
          webp: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/make%20up/IMG_20250926_1440222.webp",
          jpg: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/make%20up/IMG_20250926_1440222.jpg",
        },
        {
          src: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/make%20up/ba3beedd-744b-4c19-be27-4404e4a0821a.webp",
          fallbackSrc:
            "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/make%20up/ba3beedd-744b-4c19-be27-4404e4a0821a.jpg",
          webp: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/make%20up/ba3beedd-744b-4c19-be27-4404e4a0821a.webp",
          jpg: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/make%20up/ba3beedd-744b-4c19-be27-4404e4a0821a.jpg",
        },
      ],
      videos: [
        {
          src: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/make%20up/videos/20251213_105040.mp4",
        },
        {
          src: "https://uljzbxuxzknilubykrlw.storage.supabase.co/storage/v1/object/public/media/make%20up/videos/20251227_1142162.mp4",
        },
      ],
    },
  ],
};

